export const requiredAssets = {
  'London/London.json': require('./assets/London/London.json'),
  'London/media/cities/images/london.jpg': require('./assets/London/media/cities/images/london.jpg'),
  'London/media/cities/images/pois/london/alexander_fleming_laboratory_museum.jpg': require('./assets/London/media/cities/images/pois/london/alexander_fleming_laboratory_museum.jpg'),
  'London/media/cities/images/pois/london/all_saints_church.jpg': require('./assets/London/media/cities/images/pois/london/all_saints_church.jpg'),
  'London/media/cities/images/pois/london/apsley_house.jpg': require('./assets/London/media/cities/images/pois/london/apsley_house.jpg'),
  'London/media/cities/images/pois/london/battersea_park.jpg': require('./assets/London/media/cities/images/pois/london/battersea_park.jpg'),
  'London/media/cities/images/pois/london/battersea_power_station.jpg': require('./assets/London/media/cities/images/pois/london/battersea_power_station.jpg'),
  'London/media/cities/images/pois/london/bishops_park.jpg': require('./assets/London/media/cities/images/pois/london/bishops_park.jpg'),
  'London/media/cities/images/pois/london/british_library.jpg': require('./assets/London/media/cities/images/pois/london/british_library.jpg'),
  'London/media/cities/images/pois/london/british_museum.jpg': require('./assets/London/media/cities/images/pois/london/british_museum.jpg'),
  'London/media/cities/images/pois/london/buckingham_palace.jpg': require('./assets/London/media/cities/images/pois/london/buckingham_palace.jpg'),
  'London/media/cities/images/pois/london/bunhill_fields_burial_ground.jpg': require('./assets/London/media/cities/images/pois/london/bunhill_fields_burial_ground.jpg'),
  'London/media/cities/images/pois/london/capel_manor_gardens.jpg': require('./assets/London/media/cities/images/pois/london/capel_manor_gardens.jpg'),
  'London/media/cities/images/pois/london/chelsea_harbour_design_centre.jpg': require('./assets/London/media/cities/images/pois/london/chelsea_harbour_design_centre.jpg'),
  'London/media/cities/images/pois/london/christ_church.jpg': require('./assets/London/media/cities/images/pois/london/christ_church.jpg'),
  'London/media/cities/images/pois/london/covent_garden_piazza_and_central_market.jpg': require('./assets/London/media/cities/images/pois/london/covent_garden_piazza_and_central_market.jpg'),
  'London/media/cities/images/pois/london/design_museum.jpg': require('./assets/London/media/cities/images/pois/london/design_museum.jpg'),
  'London/media/cities/images/pois/london/ealing_town_hall.jpg': require('./assets/London/media/cities/images/pois/london/ealing_town_hall.jpg'),
  'London/media/cities/images/pois/london/fulham_palace.jpg': require('./assets/London/media/cities/images/pois/london/fulham_palace.jpg'),
  'London/media/cities/images/pois/london/hackney_town_hall.jpg': require('./assets/London/media/cities/images/pois/london/hackney_town_hall.jpg'),
  'London/media/cities/images/pois/london/hampton_court_palace.jpg': require('./assets/London/media/cities/images/pois/london/hampton_court_palace.jpg'),
  'London/media/cities/images/pois/london/kensington_palace.jpg': require('./assets/London/media/cities/images/pois/london/kensington_palace.jpg'),
  'London/media/cities/images/pois/london/kenwood_house.jpg': require('./assets/London/media/cities/images/pois/london/kenwood_house.jpg'),
  'London/media/cities/images/pois/london/lambeth_palace.jpg': require('./assets/London/media/cities/images/pois/london/lambeth_palace.jpg'),
  'London/media/cities/images/pois/london/london_eye.jpg': require('./assets/London/media/cities/images/pois/london/london_eye.jpg'),
  'London/media/cities/images/pois/london/london_transport_museum.jpg': require('./assets/London/media/cities/images/pois/london/london_transport_museum.jpg'),
  'London/media/cities/images/pois/london/madame_tussauds.jpg': require('./assets/London/media/cities/images/pois/london/madame_tussauds.jpg'),
  'London/media/cities/images/pois/london/mansion_house.jpg': require('./assets/London/media/cities/images/pois/london/mansion_house.jpg'),
  'London/media/cities/images/pois/london/marble_arch.jpg': require('./assets/London/media/cities/images/pois/london/marble_arch.jpg'),
  'London/media/cities/images/pois/london/museum_of_london.jpg': require('./assets/London/media/cities/images/pois/london/museum_of_london.jpg'),
  'London/media/cities/images/pois/london/museum_of_london_docklands.jpg': require('./assets/London/media/cities/images/pois/london/museum_of_london_docklands.jpg'),
  'London/media/cities/images/pois/london/national_portrait_gallery.jpg': require('./assets/London/media/cities/images/pois/london/national_portrait_gallery.jpg'),
  'London/media/cities/images/pois/london/natural_history_museum.jpg': require('./assets/London/media/cities/images/pois/london/natural_history_museum.jpg'),
  'London/media/cities/images/pois/london/palace_of_westminster.jpg': require('./assets/London/media/cities/images/pois/london/palace_of_westminster.jpg'),
  'London/media/cities/images/pois/london/pollocks_toy_museum.jpg': require('./assets/London/media/cities/images/pois/london/pollocks_toy_museum.jpg'),
  'London/media/cities/images/pois/london/queen_elizabeth_olympic_park.jpg': require('./assets/London/media/cities/images/pois/london/queen_elizabeth_olympic_park.jpg'),
  'London/media/cities/images/pois/london/regents_park.jpg': require('./assets/London/media/cities/images/pois/london/regents_park.jpg'),
  'London/media/cities/images/pois/london/richmond_park.jpg': require('./assets/London/media/cities/images/pois/london/richmond_park.jpg'),
  'London/media/cities/images/pois/london/royal_botanic_gardens.jpg': require('./assets/London/media/cities/images/pois/london/royal_botanic_gardens.jpg'),
  'London/media/cities/images/pois/london/sir_john_soanes_museum.jpg': require('./assets/London/media/cities/images/pois/london/sir_john_soanes_museum.jpg'),
  'London/media/cities/images/pois/london/soho_square.jpg': require('./assets/London/media/cities/images/pois/london/soho_square.jpg'),
  'London/media/cities/images/pois/london/st_martins_in_the_fields.jpg': require('./assets/London/media/cities/images/pois/london/st_martins_in_the_fields.jpg'),
  'London/media/cities/images/pois/london/st_pauls_cathedral.jpg': require('./assets/London/media/cities/images/pois/london/st_pauls_cathedral.jpg'),
  'London/media/cities/images/pois/london/tate_britain.jpg': require('./assets/London/media/cities/images/pois/london/tate_britain.jpg'),
  'London/media/cities/images/pois/london/tate_modern.jpg': require('./assets/London/media/cities/images/pois/london/tate_modern.jpg'),
  'London/media/cities/images/pois/london/the_arsenal_museum.jpg': require('./assets/London/media/cities/images/pois/london/the_arsenal_museum.jpg'),
  'London/media/cities/images/pois/london/the_cutty_sark.jpg': require('./assets/London/media/cities/images/pois/london/the_cutty_sark.jpg'),
  'London/media/cities/images/pois/london/the_jewel_tower.jpg': require('./assets/London/media/cities/images/pois/london/the_jewel_tower.jpg'),
  'London/media/cities/images/pois/london/the_royal_naval_college.jpg': require('./assets/London/media/cities/images/pois/london/the_royal_naval_college.jpg'),
  'London/media/cities/images/pois/london/the_shard.jpg': require('./assets/London/media/cities/images/pois/london/the_shard.jpg'),
  'London/media/cities/images/pois/london/tower_bridge.jpg': require('./assets/London/media/cities/images/pois/london/tower_bridge.jpg'),
  'London/media/cities/images/pois/london/trafalgar_square.jpg': require('./assets/London/media/cities/images/pois/london/trafalgar_square.jpg'),
  'London/media/cities/images/pois/london/victoria_and_albert_museum.jpg': require('./assets/London/media/cities/images/pois/london/victoria_and_albert_museum.jpg'),
  'London/media/cities/images/pois/london/westminster_abbey.jpg': require('./assets/London/media/cities/images/pois/london/westminster_abbey.jpg'),
  'New York City/New York City.json': require('./assets/New York City/New York City.json'),
  'New York City/media/cities/images/new_york_city.jpg': require('./assets/New York City/media/cities/images/new_york_city.jpg'),
  'New York City/media/cities/images/pois/new_york_city/american_museum_of_natural_history.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/american_museum_of_natural_history.jpg'),
  'New York City/media/cities/images/pois/new_york_city/balto_statue.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/balto_statue.jpg'),
  'New York City/media/cities/images/pois/new_york_city/bethesda_terrace_and_fountain.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/bethesda_terrace_and_fountain.jpg'),
  'New York City/media/cities/images/pois/new_york_city/brooklyn_bridge.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/brooklyn_bridge.jpg'),
  'New York City/media/cities/images/pois/new_york_city/brooklyn_museum.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/brooklyn_museum.jpg'),
  'New York City/media/cities/images/pois/new_york_city/cathedral_church_of_st._john_the_divine.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/cathedral_church_of_st._john_the_divine.jpg'),
  'New York City/media/cities/images/pois/new_york_city/central_park_zoo.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/central_park_zoo.jpg'),
  'New York City/media/cities/images/pois/new_york_city/childrens_museum_of_the_arts.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/childrens_museum_of_the_arts.jpg'),
  'New York City/media/cities/images/pois/new_york_city/chrysler_building.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/chrysler_building.jpg'),
  'New York City/media/cities/images/pois/new_york_city/conservatory_pond.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/conservatory_pond.jpg'),
  'New York City/media/cities/images/pois/new_york_city/daily_news_building.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/daily_news_building.jpg'),
  'New York City/media/cities/images/pois/new_york_city/dakota_building.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/dakota_building.jpg'),
  'New York City/media/cities/images/pois/new_york_city/el_museo_del_barrio.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/el_museo_del_barrio.jpg'),
  'New York City/media/cities/images/pois/new_york_city/ellis_island.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/ellis_island.jpg'),
  'New York City/media/cities/images/pois/new_york_city/empire_state_building.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/empire_state_building.jpg'),
  'New York City/media/cities/images/pois/new_york_city/flatiron_building.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/flatiron_building.jpg'),
  'New York City/media/cities/images/pois/new_york_city/fordham_college_at_lincoln_center.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/fordham_college_at_lincoln_center.jpg'),
  'New York City/media/cities/images/pois/new_york_city/fraunces_tavern.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/fraunces_tavern.jpg'),
  'New York City/media/cities/images/pois/new_york_city/friedsman_carousel.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/friedsman_carousel.jpg'),
  'New York City/media/cities/images/pois/new_york_city/grand_army_plaza.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/grand_army_plaza.jpg'),
  'New York City/media/cities/images/pois/new_york_city/grand_central_terminal.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/grand_central_terminal.jpg'),
  'New York City/media/cities/images/pois/new_york_city/grants_tomb.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/grants_tomb.jpg'),
  'New York City/media/cities/images/pois/new_york_city/high_line_park.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/high_line_park.jpg'),
  'New York City/media/cities/images/pois/new_york_city/lower_east_side_tenement_museum.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/lower_east_side_tenement_museum.jpg'),
  'New York City/media/cities/images/pois/new_york_city/manhattan_school_of_music.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/manhattan_school_of_music.jpg'),
  'New York City/media/cities/images/pois/new_york_city/metropolitan_museum_of_art.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/metropolitan_museum_of_art.jpg'),
  'New York City/media/cities/images/pois/new_york_city/museum_of_chinese_in_the_americas.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/museum_of_chinese_in_the_americas.jpg'),
  'New York City/media/cities/images/pois/new_york_city/museum_of_modern_art.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/museum_of_modern_art.jpg'),
  'New York City/media/cities/images/pois/new_york_city/museum_of_the_city_of_new_york.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/museum_of_the_city_of_new_york.jpg'),
  'New York City/media/cities/images/pois/new_york_city/museum_of_the_moving_image.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/museum_of_the_moving_image.jpg'),
  'New York City/media/cities/images/pois/new_york_city/national_september_11_memorial__museum.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/national_september_11_memorial__museum.jpg'),
  'New York City/media/cities/images/pois/new_york_city/new_york_by_gehry.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/new_york_by_gehry.jpg'),
  'New York City/media/cities/images/pois/new_york_city/one_world_trade_center.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/one_world_trade_center.jpg'),
  'New York City/media/cities/images/pois/new_york_city/rockefeller_center.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/rockefeller_center.jpg'),
  'New York City/media/cities/images/pois/new_york_city/solomon_r._guggenheim_museum.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/solomon_r._guggenheim_museum.jpg'),
  'New York City/media/cities/images/pois/new_york_city/statue_of_liberty.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/statue_of_liberty.jpg'),
  'New York City/media/cities/images/pois/new_york_city/strawberry_fields.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/strawberry_fields.jpg'),
  'New York City/media/cities/images/pois/new_york_city/the_cloisters.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/the_cloisters.jpg'),
  'New York City/media/cities/images/pois/new_york_city/the_ear_inn.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/the_ear_inn.jpg'),
  'New York City/media/cities/images/pois/new_york_city/times_square.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/times_square.jpg'),
  'New York City/media/cities/images/pois/new_york_city/usta_billie_jean_king_national_tennis_center.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/usta_billie_jean_king_national_tennis_center.jpg'),
  'New York City/media/cities/images/pois/new_york_city/washington_square_park.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/washington_square_park.jpg'),
  'New York City/media/cities/images/pois/new_york_city/whitney_museum_of_american_art.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/whitney_museum_of_american_art.jpg'),
  'New York City/media/cities/images/pois/new_york_city/williamsburg_art__historical_center.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/williamsburg_art__historical_center.jpg'),
  'New York City/media/cities/images/pois/new_york_city/willowbrook_park.jpg': require('./assets/New York City/media/cities/images/pois/new_york_city/willowbrook_park.jpg'),
  'Paris/Paris.json': require('./assets/Paris/Paris.json'),
  'Paris/media/cities/images/paris.jpg': require('./assets/Paris/media/cities/images/paris.jpg'),
  'Paris/media/cities/images/pois/paris/arc_de_triomphe_de_létoile.jpg': require('./assets/Paris/media/cities/images/pois/paris/arc_de_triomphe_de_létoile.jpg'),
  'Paris/media/cities/images/pois/paris/arènes_de_lutèce.jpg': require('./assets/Paris/media/cities/images/pois/paris/arènes_de_lutèce.jpg'),
  'Paris/media/cities/images/pois/paris/avenue_des_champs-elysées.jpg': require('./assets/Paris/media/cities/images/pois/paris/avenue_des_champs-elysées.jpg'),
  'Paris/media/cities/images/pois/paris/bercy_village.jpg': require('./assets/Paris/media/cities/images/pois/paris/bercy_village.jpg'),
  'Paris/media/cities/images/pois/paris/bois_de_boulogne.jpg': require('./assets/Paris/media/cities/images/pois/paris/bois_de_boulogne.jpg'),
  'Paris/media/cities/images/pois/paris/bourse_de_commerce_-_pinault_collection.jpg': require('./assets/Paris/media/cities/images/pois/paris/bourse_de_commerce_-_pinault_collection.jpg'),
  'Paris/media/cities/images/pois/paris/carnavalet.jpg': require('./assets/Paris/media/cities/images/pois/paris/carnavalet.jpg'),
  'Paris/media/cities/images/pois/paris/centre_georges_pompidou.jpg': require('./assets/Paris/media/cities/images/pois/paris/centre_georges_pompidou.jpg'),
  'Paris/media/cities/images/pois/paris/château_de_versailles.jpg': require('./assets/Paris/media/cities/images/pois/paris/château_de_versailles.jpg'),
  'Paris/media/cities/images/pois/paris/château_de_vincennes.jpg': require('./assets/Paris/media/cities/images/pois/paris/château_de_vincennes.jpg'),
  'Paris/media/cities/images/pois/paris/cirque_dhiver.jpg': require('./assets/Paris/media/cities/images/pois/paris/cirque_dhiver.jpg'),
  'Paris/media/cities/images/pois/paris/cité_des_sciences_et_de_lindustrie.jpg': require('./assets/Paris/media/cities/images/pois/paris/cité_des_sciences_et_de_lindustrie.jpg'),
  'Paris/media/cities/images/pois/paris/colonne_vendôme.png': require('./assets/Paris/media/cities/images/pois/paris/colonne_vendôme.png'),
  'Paris/media/cities/images/pois/paris/eiffel_tower.jpg': require('./assets/Paris/media/cities/images/pois/paris/eiffel_tower.jpg'),
  'Paris/media/cities/images/pois/paris/fondation_louis_vuitton.jpg': require('./assets/Paris/media/cities/images/pois/paris/fondation_louis_vuitton.jpg'),
  'Paris/media/cities/images/pois/paris/grande_arche_de_la_defense.jpg': require('./assets/Paris/media/cities/images/pois/paris/grande_arche_de_la_defense.jpg'),
  'Paris/media/cities/images/pois/paris/guimet_museum.jpg': require('./assets/Paris/media/cities/images/pois/paris/guimet_museum.jpg'),
  'Paris/media/cities/images/pois/paris/hall_of_mirrors.jpg': require('./assets/Paris/media/cities/images/pois/paris/hall_of_mirrors.jpg'),
  'Paris/media/cities/images/pois/paris/i_love_you_wall.jpg': require('./assets/Paris/media/cities/images/pois/paris/i_love_you_wall.jpg'),
  'Paris/media/cities/images/pois/paris/jacquemart-andre_museum.jpg': require('./assets/Paris/media/cities/images/pois/paris/jacquemart-andre_museum.jpg'),
  'Paris/media/cities/images/pois/paris/jardin_des_tuileries.jpg': require('./assets/Paris/media/cities/images/pois/paris/jardin_des_tuileries.jpg'),
  'Paris/media/cities/images/pois/paris/la_bibliothèque_nationale_de_france.jpg': require('./assets/Paris/media/cities/images/pois/paris/la_bibliothèque_nationale_de_france.jpg'),
  'Paris/media/cities/images/pois/paris/la_conciergerie.jpg': require('./assets/Paris/media/cities/images/pois/paris/la_conciergerie.jpg'),
  'Paris/media/cities/images/pois/paris/lassemblée_nationale.jpg': require('./assets/Paris/media/cities/images/pois/paris/lassemblée_nationale.jpg'),
  'Paris/media/cities/images/pois/paris/le_grand_palais.jpg': require('./assets/Paris/media/cities/images/pois/paris/le_grand_palais.jpg'),
  'Paris/media/cities/images/pois/paris/le_marais.jpg': require('./assets/Paris/media/cities/images/pois/paris/le_marais.jpg'),
  'Paris/media/cities/images/pois/paris/le_palais_royal.jpg': require('./assets/Paris/media/cities/images/pois/paris/le_palais_royal.jpg'),
  'Paris/media/cities/images/pois/paris/les_archives_nationales.jpg': require('./assets/Paris/media/cities/images/pois/paris/les_archives_nationales.jpg'),
  'Paris/media/cities/images/pois/paris/les_catacombes_de_paris.jpg': require('./assets/Paris/media/cities/images/pois/paris/les_catacombes_de_paris.jpg'),
  'Paris/media/cities/images/pois/paris/les_invalides.jpg': require('./assets/Paris/media/cities/images/pois/paris/les_invalides.jpg'),
  'Paris/media/cities/images/pois/paris/manufacture_des_gobelins.jpg': require('./assets/Paris/media/cities/images/pois/paris/manufacture_des_gobelins.jpg'),
  'Paris/media/cities/images/pois/paris/musée_de_linstitut_du_monde_arabe.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_de_linstitut_du_monde_arabe.jpg'),
  'Paris/media/cities/images/pois/paris/musée_de_lorangerie.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_de_lorangerie.jpg'),
  'Paris/media/cities/images/pois/paris/musée_de_montmartre.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_de_montmartre.jpg'),
  'Paris/media/cities/images/pois/paris/musée_delacroix.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_delacroix.jpg'),
  'Paris/media/cities/images/pois/paris/musée_des_arts_décoratifs.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_des_arts_décoratifs.jpg'),
  'Paris/media/cities/images/pois/paris/musée_dorsay.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_dorsay.jpg'),
  'Paris/media/cities/images/pois/paris/musée_edith_piaf.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_edith_piaf.jpg'),
  'Paris/media/cities/images/pois/paris/musée_gustave_moreau.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_gustave_moreau.jpg'),
  'Paris/media/cities/images/pois/paris/musée_marmottan-monet.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_marmottan-monet.jpg'),
  'Paris/media/cities/images/pois/paris/musée_national_du_moyen_âge.jpg': require('./assets/Paris/media/cities/images/pois/paris/musée_national_du_moyen_âge.jpg'),
  'Paris/media/cities/images/pois/paris/mémorial_de_la_shoah.jpg': require('./assets/Paris/media/cities/images/pois/paris/mémorial_de_la_shoah.jpg'),
  'Paris/media/cities/images/pois/paris/notre_dame_cathedral.jpg': require('./assets/Paris/media/cities/images/pois/paris/notre_dame_cathedral.jpg'),
  'Paris/media/cities/images/pois/paris/opera_garnier.jpg': require('./assets/Paris/media/cities/images/pois/paris/opera_garnier.jpg'),
  'Paris/media/cities/images/pois/paris/palais_de_chaillot.jpg': require('./assets/Paris/media/cities/images/pois/paris/palais_de_chaillot.jpg'),
  'Paris/media/cities/images/pois/paris/palais_du_luxembourg.jpg': require('./assets/Paris/media/cities/images/pois/paris/palais_du_luxembourg.jpg'),
  'Paris/media/cities/images/pois/paris/panthéon.jpg': require('./assets/Paris/media/cities/images/pois/paris/panthéon.jpg'),
  'Paris/media/cities/images/pois/paris/picasso_museum.jpg': require('./assets/Paris/media/cities/images/pois/paris/picasso_museum.jpg'),
  'Paris/media/cities/images/pois/paris/place_de_la_bastille.jpg': require('./assets/Paris/media/cities/images/pois/paris/place_de_la_bastille.jpg'),
  'Paris/media/cities/images/pois/paris/place_de_la_concorde.jpg': require('./assets/Paris/media/cities/images/pois/paris/place_de_la_concorde.jpg'),
  'Paris/media/cities/images/pois/paris/père-lachaise_cemetery.jpg': require('./assets/Paris/media/cities/images/pois/paris/père-lachaise_cemetery.jpg'),
  'Paris/media/cities/images/pois/paris/rodin_museum.jpg': require('./assets/Paris/media/cities/images/pois/paris/rodin_museum.jpg'),
  'Paris/media/cities/images/pois/paris/sacré_coeur.jpg': require('./assets/Paris/media/cities/images/pois/paris/sacré_coeur.jpg'),
  'Paris/media/cities/images/pois/paris/sainte-chapelle.jpg': require('./assets/Paris/media/cities/images/pois/paris/sainte-chapelle.jpg'),
  'Paris/media/cities/images/pois/paris/the_louvre.jpg': require('./assets/Paris/media/cities/images/pois/paris/the_louvre.jpg'),
  'Paris/media/cities/images/pois/paris/église_saint-eustache.jpg': require('./assets/Paris/media/cities/images/pois/paris/église_saint-eustache.jpg'),
  'Paris/media/cities/images/pois/paris/église_saint-jacques-du-haut-pas.jpg': require('./assets/Paris/media/cities/images/pois/paris/église_saint-jacques-du-haut-pas.jpg'),
  'Rome/Rome.json': require('./assets/Rome/Rome.json'),
  'Rome/media/cities/images/pois/rome/ara_pacis.jpg': require('./assets/Rome/media/cities/images/pois/rome/ara_pacis.jpg'),
  'Rome/media/cities/images/pois/rome/arch_of_constantine.jpg': require('./assets/Rome/media/cities/images/pois/rome/arch_of_constantine.jpg'),
  'Rome/media/cities/images/pois/rome/arch_of_titus.jpg': require('./assets/Rome/media/cities/images/pois/rome/arch_of_titus.jpg'),
  'Rome/media/cities/images/pois/rome/basilica_and_catacombs_of_san_sebastiano.jpg': require('./assets/Rome/media/cities/images/pois/rome/basilica_and_catacombs_of_san_sebastiano.jpg'),
  'Rome/media/cities/images/pois/rome/basilica_dei_santi_giovanni_e_paolo_al_celio.jpg': require('./assets/Rome/media/cities/images/pois/rome/basilica_dei_santi_giovanni_e_paolo_al_celio.jpg'),
  'Rome/media/cities/images/pois/rome/borghese_gardens.jpg': require('./assets/Rome/media/cities/images/pois/rome/borghese_gardens.jpg'),
  'Rome/media/cities/images/pois/rome/castel_santangelo.jpg': require('./assets/Rome/media/cities/images/pois/rome/castel_santangelo.jpg'),
  'Rome/media/cities/images/pois/rome/centrale_montemartini_museum.jpg': require('./assets/Rome/media/cities/images/pois/rome/centrale_montemartini_museum.jpg'),
  'Rome/media/cities/images/pois/rome/chiesa_del_gesù.jpg': require('./assets/Rome/media/cities/images/pois/rome/chiesa_del_gesù.jpg'),
  'Rome/media/cities/images/pois/rome/colosseum.jpg': require('./assets/Rome/media/cities/images/pois/rome/colosseum.jpg'),
  'Rome/media/cities/images/pois/rome/column_of_marcus_aurelius.jpg': require('./assets/Rome/media/cities/images/pois/rome/column_of_marcus_aurelius.jpg'),
  'Rome/media/cities/images/pois/rome/crypta_balbi.jpg': require('./assets/Rome/media/cities/images/pois/rome/crypta_balbi.jpg'),
  'Rome/media/cities/images/pois/rome/enoteca_ferrara.jpg': require('./assets/Rome/media/cities/images/pois/rome/enoteca_ferrara.jpg'),
  'Rome/media/cities/images/pois/rome/galleria_nazionale_darte_moderna_gnam.jpg': require('./assets/Rome/media/cities/images/pois/rome/galleria_nazionale_darte_moderna_gnam.jpg'),
  'Rome/media/cities/images/pois/rome/il_gianicolo.jpg': require('./assets/Rome/media/cities/images/pois/rome/il_gianicolo.jpg'),
  'Rome/media/cities/images/pois/rome/maxxi.jpg': require('./assets/Rome/media/cities/images/pois/rome/maxxi.jpg'),
  'Rome/media/cities/images/pois/rome/museo_capitolino.jpg': require('./assets/Rome/media/cities/images/pois/rome/museo_capitolino.jpg'),
  'Rome/media/cities/images/pois/rome/museo_della_civilta_romana_museum_of_romes_civilization.jpg': require('./assets/Rome/media/cities/images/pois/rome/museo_della_civilta_romana_museum_of_romes_civilization.jpg'),
  'Rome/media/cities/images/pois/rome/museum_of_the_walls.jpg': require('./assets/Rome/media/cities/images/pois/rome/museum_of_the_walls.jpg'),
  'Rome/media/cities/images/pois/rome/palatine_hill.jpg': require('./assets/Rome/media/cities/images/pois/rome/palatine_hill.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_barberini.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_barberini.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_crivelli.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_crivelli.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_doria_pamphilj.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_doria_pamphilj.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_madama.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_madama.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_spada.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_spada.jpg'),
  'Rome/media/cities/images/pois/rome/palazzo_taverna.jpg': require('./assets/Rome/media/cities/images/pois/rome/palazzo_taverna.jpg'),
  'Rome/media/cities/images/pois/rome/piazza_navona.jpg': require('./assets/Rome/media/cities/images/pois/rome/piazza_navona.jpg'),
  'Rome/media/cities/images/pois/rome/piazza_venezia.jpg': require('./assets/Rome/media/cities/images/pois/rome/piazza_venezia.jpg'),
  'Rome/media/cities/images/pois/rome/quartiere_coppedè_part_of_the_neighborhood_of_trieste.jpg': require('./assets/Rome/media/cities/images/pois/rome/quartiere_coppedè_part_of_the_neighborhood_of_trieste.jpg'),
  'Rome/media/cities/images/pois/rome/salvatore_ferragamo.jpg': require('./assets/Rome/media/cities/images/pois/rome/salvatore_ferragamo.jpg'),
  'Rome/media/cities/images/pois/rome/san_clemente.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_clemente.jpg'),
  'Rome/media/cities/images/pois/rome/san_francesco_a_ripa.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_francesco_a_ripa.jpg'),
  'Rome/media/cities/images/pois/rome/san_giovanni_in_laterano.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_giovanni_in_laterano.jpg'),
  'Rome/media/cities/images/pois/rome/san_luigi_dei_francesi.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_luigi_dei_francesi.jpg'),
  'Rome/media/cities/images/pois/rome/san_nicola_in_carcere.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_nicola_in_carcere.jpg'),
  'Rome/media/cities/images/pois/rome/san_pietro_in_vincoli.jpg': require('./assets/Rome/media/cities/images/pois/rome/san_pietro_in_vincoli.jpg'),
  'Rome/media/cities/images/pois/rome/santa_cecilia_in_trastevere.jpg': require('./assets/Rome/media/cities/images/pois/rome/santa_cecilia_in_trastevere.jpg'),
  'Rome/media/cities/images/pois/rome/santa_maria_del_popolo.jpg': require('./assets/Rome/media/cities/images/pois/rome/santa_maria_del_popolo.jpg'),
  'Rome/media/cities/images/pois/rome/santa_maria_in_aracoeli.jpg': require('./assets/Rome/media/cities/images/pois/rome/santa_maria_in_aracoeli.jpg'),
  'Rome/media/cities/images/pois/rome/santa_maria_in_trastevere.jpg': require('./assets/Rome/media/cities/images/pois/rome/santa_maria_in_trastevere.jpg'),
  'Rome/media/cities/images/pois/rome/santa_maria_maggiore.jpg': require('./assets/Rome/media/cities/images/pois/rome/santa_maria_maggiore.jpg'),
  'Rome/media/cities/images/pois/rome/santignazio.jpg': require('./assets/Rome/media/cities/images/pois/rome/santignazio.jpg'),
  'Rome/media/cities/images/pois/rome/santissima_trinità_dei_monti.jpg': require('./assets/Rome/media/cities/images/pois/rome/santissima_trinità_dei_monti.jpg'),
  'Rome/media/cities/images/pois/rome/santivo_alla_sapienza.jpg': require('./assets/Rome/media/cities/images/pois/rome/santivo_alla_sapienza.jpg'),
  'Rome/media/cities/images/pois/rome/santo_stefano_rotondo.jpg': require('./assets/Rome/media/cities/images/pois/rome/santo_stefano_rotondo.jpg'),
  'Rome/media/cities/images/pois/rome/st._peters_basilica.jpg': require('./assets/Rome/media/cities/images/pois/rome/st._peters_basilica.jpg'),
  'Rome/media/cities/images/pois/rome/st._peters_square.jpg': require('./assets/Rome/media/cities/images/pois/rome/st._peters_square.jpg'),
  'Rome/media/cities/images/pois/rome/terme_di_caracalla.jpg': require('./assets/Rome/media/cities/images/pois/rome/terme_di_caracalla.jpg'),
  'Rome/media/cities/images/pois/rome/the_catacombs_of_san_callisto.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_catacombs_of_san_callisto.jpg'),
  'Rome/media/cities/images/pois/rome/the_pantheon.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_pantheon.jpg'),
  'Rome/media/cities/images/pois/rome/the_roman_forum.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_roman_forum.jpg'),
  'Rome/media/cities/images/pois/rome/the_spanish_steps.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_spanish_steps.jpg'),
  'Rome/media/cities/images/pois/rome/the_tempietto.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_tempietto.jpg'),
  'Rome/media/cities/images/pois/rome/the_vatican_museum.jpg': require('./assets/Rome/media/cities/images/pois/rome/the_vatican_museum.jpg'),
  'Rome/media/cities/images/pois/rome/theatre_of_marcellus.jpg': require('./assets/Rome/media/cities/images/pois/rome/theatre_of_marcellus.jpg'),
  'Rome/media/cities/images/pois/rome/trajans_markets.jpg': require('./assets/Rome/media/cities/images/pois/rome/trajans_markets.jpg'),
  'Rome/media/cities/images/pois/rome/trevi_fountain.jpg': require('./assets/Rome/media/cities/images/pois/rome/trevi_fountain.jpg'),
  'Rome/media/cities/images/pois/rome/via_veneto.jpg': require('./assets/Rome/media/cities/images/pois/rome/via_veneto.jpg'),
  'Rome/media/cities/images/pois/rome/villa_borghese.jpg': require('./assets/Rome/media/cities/images/pois/rome/villa_borghese.jpg'),
  'Rome/media/cities/images/pois/rome/villa_dei_quintilii.jpg': require('./assets/Rome/media/cities/images/pois/rome/villa_dei_quintilii.jpg'),
  'Rome/media/cities/images/pois/rome/villa_farnesina.jpg': require('./assets/Rome/media/cities/images/pois/rome/villa_farnesina.jpg'),
  'Rome/media/cities/images/pois/rome/villa_medici.jpg': require('./assets/Rome/media/cities/images/pois/rome/villa_medici.jpg'),
  'Rome/media/cities/images/pois/rome/vittorio_emanuele_monument.jpg': require('./assets/Rome/media/cities/images/pois/rome/vittorio_emanuele_monument.jpg'),
  'Rome/media/cities/images/rome.jpg': require('./assets/Rome/media/cities/images/rome.jpg'),
  'adaptive-icon.png': require('./assets/adaptive-icon.png'),
  'barcelona.png': require('./assets/barcelona.png'),
  'drink.png': require('./assets/drink.png'),
  'eat.png': require('./assets/eat.png'),
  'favicon.png': require('./assets/favicon.png'),
  'icon.png': require('./assets/icon.png'),
  'istanbul.png': require('./assets/istanbul.png'),
  'las_vegas.png': require('./assets/las_vegas.png'),
  'london_cover.png': require('./assets/london_cover.png'),
  'london_iap.png': require('./assets/london_iap.png'),
  'london_stamp.png': require('./assets/london_stamp.png'),
  'los_angeles.png': require('./assets/los_angeles.png'),
  'new_york_city_cover.png': require('./assets/new_york_city_cover.png'),
  'new_york_city_iap.png': require('./assets/new_york_city_iap.png'),
  'new_york_city_stamp.png': require('./assets/new_york_city_stamp.png'),
  'onboarding_hero.png': require('./assets/onboarding_hero.png'),
  'paris_cover.png': require('./assets/paris_cover.png'),
  'paris_iap.png': require('./assets/paris_iap.png'),
  'paris_stamp.png': require('./assets/paris_stamp.png'),
  'play.png': require('./assets/play.png'),
  'rome_cover.png': require('./assets/rome_cover.png'),
  'rome_iap.png': require('./assets/rome_iap.png'),
  'rome_stamp.png': require('./assets/rome_stamp.png'),
  'san_francisco_cover.png': require('./assets/san_francisco_cover.png'),
  'san_francisco_stamp.png': require('./assets/san_francisco_stamp.png'),
  'see.png': require('./assets/see.png'),
  'shop.png': require('./assets/shop.png'),
  'sleep.png': require('./assets/sleep.png'),
  'splash-icon.png': require('./assets/splash-icon.png'),
  'title_icon.png': require('./assets/title_icon.png'),
  'title_image.png': require('./assets/title_image.png'),
  'tokyo_cover.png': require('./assets/tokyo_cover.png'),
  'tokyo_stamp.png': require('./assets/tokyo_stamp.png')
};
